### ISSUE TITLE
Server raised fault: 'No matches returned for Username

### ISSUE THREAD

**Issue by iloveOREO** [enricobacis/wos#26]
I receive the issue “No matches returned for Username”，but I can log in Wos with my browser.
Can you fix that？

**Comment by enricobacis** [comment]
Please read the readme before opening issues: https://github.com/enricobacis/wos/blob/master/README.rst#faq-i-cannot-connect-

**Comment by iloveOREO** [comment]
I had read the readme.
My network can access the wos,so i think there should be a way to solve this problem.

**Comment by enricobacis** [comment]
Hi @iloveOREO, probably I was not clear enough in my previous answer.

The FAQ in the README clearly states your case. I do understand that you can access the WOS website from your network, but the website access and the API access (used in this project) are two separated products, and the website access does not imply the API access (since Thomson Reuters bills them separately).

This project does not scrape the website (which would violate the terms of usage) but invokes the WWS APIs offered by Thomson Reuters. Thus there is nothing this project can do to help you.

If you are still not convinced, please contact Thomson Reuters support and ask if you have the WWS access and please re-open the issue only if you have that access, because there is nothing I can do if you don't have it.

**Comment by iloveOREO** [comment]
I see.Thank you.
