### ISSUE TITLE
getting syntax error

### ISSUE THREAD

**Issue by ask1710** [enricobacis/wos#9]
Hi @enricobacis,
I downloaded your wos client using 'pip install wos'. In python console, when I 'import wos', there's no problem. But after that when I try to use any options with wos, like 'wos -h', 'wos --help', 'wos --lite' or 'wos -u 'username' -p 'password' connect' , I get a syntax error.
I also tried your program example with myUsername and password. But when I ran it, it said:
WebFault: b"Server raised fault: 'No matches returned for Username myUsername'"
I can sign in to web of science without any problem through browser with the same username and password.
What could be going wrong?
Would appreciate your help!

**Comment by enricobacis** [comment]
Hi @ask1710,

you don't need to open the python console to run the `wos` commands, just run them in your shell, in fact `wos -h` is not a valid python statement, but it's a valid shell command with its arguments.

For the second part of the issue, you need the WWS ( web services ) access in order to be able to use this library to access web of science. So you probably have the web access but not the web service one. You should contact Thomson Reuters support to have more information on this.

**Comment by ask1710** [comment]
Thanks for prompt reply @enricobacis !
I'm new to using web services and also python. So didn't know about it. 
Just put in a request with TR for web services access.
